language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - pip install --upgrade pytest

install:
  - python setup.py install
  - pip install -r dev-requirements.txt

script: py.test -vvv ./tests
